import java.awt.Dimension;
import java.awt.Toolkit;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

public class ChefMedecin extends javax.swing.JFrame {

    /**
     * Creates new form ChefMedecin
     */
    public ChefMedecin() {
        initComponents();

        // Center the window on the screen
        Toolkit toolkit = getToolkit();
        Dimension size = toolkit.getScreenSize();
        setLocation(size.width / 2 - getWidth() / 2, size.height / 2 - getHeight() / 2);

        // Populate the reservation table with mock data
        update_Table_Reservation();
    }

    private void update_Table_Reservation() {
        try {
            // Mock data for reservations
            Object[][] data = {
                {1, "123456789", "2023-10-01", "10:00", "Type1", "Service1", 1},
                {2, "987654321", "2023-10-02", "11:00", "Type2", "Service2", 1},
                {3, "456789123", "2023-10-03", "12:00", "Type3", "Service3", 1}
            };

            // Get the table model and clear existing data
            DefaultTableModel model = (DefaultTableModel) reservation_Table.getModel();
            model.setRowCount(0);

            // Add mock data to the table
            for (Object[] row : data) {
                model.addRow(row);
            }
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "Error updating table: " + ex.getMessage());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    private void initComponents() {

        jScrollPane5 = new javax.swing.JScrollPane();
        reservation_Table = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        NumResText = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        dateText = new javax.swing.JLabel();
        HeureText = new javax.swing.JLabel();
        TypeText = new javax.swing.JLabel();
        ServiceText = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel35 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        nssTextField = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        reservation_Table.setModel(new javax.swing.table.DefaultTableModel(
            new Object[][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String[] {
                "num_res", "NSS", "Date", "Heure", "Type", "Service", "Etat"
            }
        ));
        reservation_Table.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                reservation_TableMouseClicked(evt);
            }
        });
        jScrollPane5.setViewportView(reservation_Table);

        jLabel1.setFont(new java.awt.Font("Helvetica Neue", 0, 18));
        jLabel1.setText("Select Reservation:");

        jLabel29.setFont(new java.awt.Font("Eras Medium ITC", 0, 20));
        jLabel29.setText("Numero Reservation :");

        NumResText.setFont(new java.awt.Font("Helvetica Neue", 0, 18));
        NumResText.setText("0");

        jLabel34.setFont(new java.awt.Font("Eras Medium ITC", 0, 20));
        jLabel34.setText("Date :");

        jLabel33.setFont(new java.awt.Font("Eras Medium ITC", 0, 20));
        jLabel33.setText("Type :");

        jLabel37.setFont(new java.awt.Font("Eras Medium ITC", 0, 20));
        jLabel37.setText("Service :");

        jLabel31.setFont(new java.awt.Font("Eras Medium ITC", 0, 20));
        jLabel31.setText("Heure :");

        jButton1.setText("Choisir medcin");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel35.setFont(new java.awt.Font("Eras Medium ITC", 0, 20));
        jLabel35.setText("NSS :");

        jButton2.setText("Choisir Infirmier");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addGap(54, 54, 54)
                        .addComponent(jButton2))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel29)
                            .addComponent(jLabel35)
                            .addComponent(jLabel34)
                            .addComponent(jLabel31)
                            .addComponent(jLabel33)
                            .addComponent(jLabel37))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(NumResText)
                            .addComponent(nssTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(dateText)
                            .addComponent(HeureText)
                            .addComponent(TypeText)
                            .addComponent(ServiceText))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 100, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 617, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(86, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 479, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel29)
                            .addComponent(NumResText))
                        .addGap(13, 13, 13)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel35)
                            .addComponent(nssTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel34)
                            .addComponent(dateText))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel31)
                            .addComponent(HeureText))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel33)
                            .addComponent(TypeText))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel37)
                            .addComponent(ServiceText))
                        .addGap(47, 47, 47)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton1)
                            .addComponent(jButton2))))
                .addGap(22, 22, 22))
        );

        pack();
    }

    private void reservation_TableMouseClicked(java.awt.event.MouseEvent evt) {
        int row = reservation_Table.getSelectedRow();
        String num_res = reservation_Table.getModel().getValueAt(row, 0).toString();
        String nss = reservation_Table.getModel().getValueAt(row, 1).toString();
        String date = reservation_Table.getModel().getValueAt(row, 2).toString();
        String time = reservation_Table.getModel().getValueAt(row, 3).toString();
        String type = reservation_Table.getModel().getValueAt(row, 4).toString();
        String service = reservation_Table.getModel().getValueAt(row, 5).toString();

        // Set the values in the text fields and labels
        NumResText.setText(num_res);
        nssTextField.setText(nss);
        dateText.setText(date);
        HeureText.setText(time);
        TypeText.setText(type);
        ServiceText.setText(service);
    }

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {
        String nss = nssTextField.getText();
        String date = dateText.getText();
        String time = HeureText.getText();
        String service = ServiceText.getText();

        // Mock action for choosing a doctor
        JOptionPane.showMessageDialog(this, "Médecin choisi pour NSS: " + nss + ", Date: " + date + ", Heure: " + time + ", Service: " + service);
    }

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {
        String nss = nssTextField.getText();
        String date = dateText.getText();
        String time = HeureText.getText();
        String service = ServiceText.getText();

        // Mock action for choosing a nurse
        JOptionPane.showMessageDialog(this, "Infirmier choisi pour NSS: " + nss + ", Date: " + date + ", Heure: " + time + ", Service: " + service);
    }

    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(() -> {
            new ChefMedecin().setVisible(true);
        });
    }

    // Variables declaration
    private javax.swing.JLabel HeureText;
    private javax.swing.JLabel NumResText;
    private javax.swing.JLabel ServiceText;
    private javax.swing.JLabel TypeText;
    private javax.swing.JLabel dateText;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTextField nssTextField;
    private javax.swing.JTable reservation_Table;
}